### ISSUE TITLE
complie error

### ISSUE THREAD

**Issue by yuthstyle88** [softprops/again#1]
--> src/main.rs:7:10
  |
7 | #[tokio::main]
  |          ^^^^ could not find `main` in `tokio`

error[E0423]: expected value, found struct `RetryPolicy`
  --> src/main.rs:10:18
   |
10 |     let policy = RetryPolicy.exponential(Duration::from_millis(200))
   |                  ^^^^^^^^^^^------------
   |                  |
   |                  help: use the path separator to refer to an item: `RetryPolicy::exponential`

warning: unused `#[macro_use]` import
 --> src/main.rs:1:1

**Comment by softprops** [comment]
Hi.

It looks like you are trying to leverage tokio buy don't have tokio as a dependency of your project
You'll want something like

```yaml
tokio = { version = "0.2", features = ["rt-threaded","macros"] }
```

**Comment by yuthstyle88** [comment]
thank you
________________________________

**Comment by yuthstyle88** [comment]
error[E0423]: expected value, found struct `RetryPolicy`
  --> src/main.rs:10:18
   |
10 |     let policy = RetryPolicy.exponential(Duration::from_millis(200))
   |                  ^^^^^^^^^^^------------
   |                  |
   |                  help: use the path separator to refer to an item: `RetryPolicy::exponential`


error again
________________________________

**Comment by yuthstyle88** [comment]
#[macro_use]
extern crate reqwest;
use reqwest::Error;
use again::RetryPolicy;
use std::time::Duration;

#[tokio::main]
async fn main() -> Result<(), reqwest::Error> {
    pretty_env_logger::init();
    let policy = RetryPolicy::exponential(Duration::from_millis(200))
        .with_max_retries(10)
        .with_jitter(true);
    again::retry(|| reqwest::get("https://api.you.com")).await?;
    Ok(())
}

work ...
________________________________

**Comment by yuthstyle88** [comment]
how to work with cookie_store for reqwest

**Comment by softprops** [comment]
I fixed the readme example. Could you explain what you are trying to do with a cookie store? I'm missing the context

**Comment by yuthstyle88** [comment]
I try to do  login system  and  persistent  instant  cookie  state alive when move to new url

**Comment by softprops** [comment]
Can you paste your code for reference. I'm having a hard time following without the extra context

**Comment by yuthstyle88** [comment]
use std::error::Error;
use std::time::Duration;
use again::RetryPolicy;

#[tokio::main]
async fn main() -> Result<(), Box<dyn Error>> {
    pretty_env_logger::init();
    let policy = RetryPolicy::exponential(Duration::from_millis(200))
        .with_max_retries(10)
        .with_jitter(true);
    static APP_USER_AGENT: &str = "Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1";
    let client = reqwest::Client::builder()
        .cookie_store(true)
        .user_agent(APP_USER_AGENT)
        .build()?;
    policy.retry(||  client.get("https://xxxx.com/")).await?;
    Ok(())
}

**Comment by softprops** [comment]
@yuthstyle88 can you show the compile error you're seeing?

**Comment by yuthstyle88** [comment]
now it work a  problem come from  my source thank you.
